### ISSUE TITLE
build :: add docker file

### ISSUE THREAD

**Issue by miraexhoi** [dnd-side-project/dnd-11th-10-backend#14]
**기능 요청이 문제와 관련되어 있습니까? 설명해주세요.**
Docker 파일 추가

**원하는 솔루션 설명**
Docke 파일 추가

**Comment by apptie** [comment]
git commit convention의 type 중 docs는 documentation으로 문서와 관련된 type이라 docs는 어울리지 않는 것 같고, chore나 build 등 설정에 관련된 type을 명시하는게 좋을 것 같습니다 

이전 github action 스크립트 추가 시 build를 사용하셨으니 이것도 build로 통일시키는건 어떨까요

**Comment by miraexhoi** [comment]
넵 변경하겠습니다
