### ISSUE TITLE
feature :: add word search function

### ISSUE THREAD

**Issue by miraexhoi** [dnd-side-project/dnd-11th-10-backend#25]
**기능 요청이 문제와 관련되어 있습니까? 설명해주세요.**
단어 검색 및 연관검색어 기능 추가

**원하는 솔루션 설명**
- [x] ~~검색한 키워드에 따른 연관검색어~~
- [x] 단어 검색 결과 조회

**Comment by miraexhoi** [comment]
@apptie 
용어 검색어 자동완성 작업이 제 담당인걸로 알고 있는데, 파일을 확인해 보니 이미 API가 구현되어 있네요
덕분에 남은 검색 결과 조회 API만 구현하도록 하겠습니다 ~ 감사합니다!

**Comment by apptie** [comment]
제 파트인줄 알았는데 어...헷갈렸나 봅니다 죄송합니다
